simpleMethod:
	g++ -Wall -I/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/include/ -L/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/lib simpleMethod.cpp -I/home/anouk/2018/cours/INF569/projet/FADBAD++ -lProfilPackages -lProfil -lBias -llr -lm 
                       
taylorStep1:
	g++ -Wall -I/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/include/ -L/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/lib taylorStep1.cpp -I/home/anouk/2018/cours/INF569/projet/FADBAD++ -lProfilPackages -lProfil -lBias -llr -lm 

eij:
	g++ -Wall -I/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/include/ -L/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/lib eijgenraamsMethod.cpp -I/home/anouk/2018/cours/INF569/projet/FADBAD++ -lProfilPackages -lProfil -lBias -llr -lm 

eijG:
	g++ -Wall -I/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/include/ -L/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/lib eijenGr.cpp -I/home/anouk/2018/cours/INF569/projet/FADBAD++ -lProfilPackages -lProfil -lBias -llr -lm 
                       