all:
	gcc -Wall -I/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/include/ -L/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/lib simpleBoundingBoxEx.cpp -lProfilPackages -lProfil -lBias -llr -lm 
