simpleBoundingBox:
	gcc -Wall -I/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/include/ -L/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/lib simpleBoundingBoxEx.cpp -lProfilPackages -lProfil -lBias -llr -lm 

testfadbad:
	g++ -Wall -I/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/include/ -L/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/lib testfadbad.cpp -I/home/anouk/2018/cours/INF569/projet/FADBAD++ -lProfilPackages -lProfil -lBias -llr -lm 

testfadbadT:
	g++ -Wall -I/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/include/ -L/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/lib testfadbadT.cpp -I/home/anouk/2018/cours/INF569/projet/FADBAD++ -lProfilPackages -lProfil -lBias -llr -lm 

testfadbadTBis:
	g++ -Wall -I/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/include/ -L/home/anouk/2018/cours/INF569/projet/Profil-2.0.8/lib testFadbadTBis.cpp -I/home/anouk/2018/cours/INF569/projet/FADBAD++ -lProfilPackages -lProfil -lBias -llr -lm 